services:

  postgres:
    image: postgres:17
    container_name: workflow-postgres

    environment:
      POSTGRES_DB: workflowdb
      POSTGRES_USER: workflowuser
      POSTGRES_PASSWORD: workflowpass

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: workflow-backend

    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000

    depends_on:
      - postgres

    ports:
      - "8080:8080"

volumes:
  postgres_data: