server:
    port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet: 
    multipart: 
      max-file-size: 10485760
      max-request-size: 10485760
      
jwt:
  secret: mylogestsecretkeyforenterpriseworkflowmanagement222242
  expiration: 900000

refresh-token:
  expiration: 604800000 

management:
  endpoints:
    web: 
      exposure: 
        include: health,info,metrics,loggers
  endpoint:
    health: 
      show-details: always 

logging: 
  level: 
    root: INFO
    com.workflowsystem.demo: DEBUG
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/workflow.log

file: 
  upload-dir: uploads
    